export const DISPLAY_ALERT = 'SHOW_ALERT';

export const PROTECTED_ALERT = 'PROTECTED_ALERT';

export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SHOW_TOGGLE_PROFILE = 'SHOW_TOGGLE_PROFILE';

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';

export const CLEAR_VALUES = 'CLEAR_VALUES';

export const CREATE_ANIMAL_BEGIN = 'CREATE_ANIMAL_BEGIN';
export const CREATE_ANIMAL_SUCCESS = 'CREATE_ANIMAL_SUCCESS';
export const CREATE_ANIMAL_ERROR = 'CREATE_ANIMAL_ERROR';

export const GET_ANIMAL_BEGIN = 'GET_ANIMAL_BEGIN';
export const GET_ANIMAL_SUCCESS = 'GET_ANIMAL_SUCCESS';

export const UPLOAD_PHOTO_BEGIN = 'UPLOAD_PHOTO_BEGIN';
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS';
export const UPLOAD_PHOTO_ERROR = 'UPLOAD_PHOTO_ERROR';

export const GET_ONEANIMAL_BEGIN = 'GET_ONEANIMAL_BEGIN';
export const GET_ONEANIMAL_SUCCESS = 'GET_ONEANIMAL_SUCCESS';

export const SET_EDIT_ANIMAL = 'SET_EDIT_ANIMAL';

export const DELETE_ANIMAL_BEGIN = 'DELETE_ANIMAL_BEGIN';

export const EDIT_ANIMAL_BEGIN = 'EDIT_ANIMAL_BEGIN';
export const EDIT_ANIMAL_SUCCESS = 'EDIT_ANIMAL_SUCCESS';
export const EDIT_ANIMAL_ERROR = 'EDIT_ANIMAL_ERROR';

export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const CHANGE_PAGE = 'CHANGE_PAGE';
